name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Generate Snake Animation
      uses: Platane/snk@v2
      with:
        github_user_name: M-craspo
        outputs: dist/snake.svg

    - name: Commit and Push Snake Animation
      run: |
        git config --global user.name "M-craspo"
        git config --global user.email "elbahymahmoud206@gmail.com"
        git add -A
        git commit -m "Generated snake animation"
        git push
